version: '3.8'

services:
  gupiao:
    build: .
    container_name: gupiao_app
    ports:
      - "8501:8501"
    volumes:
      # 配置文件挂载（可以在宿主机修改配置）
      - ./config:/app/config
      # 缓存目录挂载（持久化缓存数据）
      - gupiao_cache:/tmp/stock_cache
      # 日志目录挂载
      - gupiao_logs:/var/log
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Shanghai
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - gupiao_network

  # Nginx反向代理（可选）
  nginx:
    image: nginx:alpine
    container_name: gupiao_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl  # SSL证书目录（可选）
    depends_on:
      - gupiao
    restart: unless-stopped
    networks:
      - gupiao_network

  # Redis缓存（可选，用于高性能缓存）
  redis:
    image: redis:alpine
    container_name: gupiao_redis
    ports:
      - "6379:6379"
    volumes:
      - gupiao_redis_data:/data
    restart: unless-stopped
    networks:
      - gupiao_network

volumes:
  gupiao_cache:
    driver: local
  gupiao_logs:
    driver: local
  gupiao_redis_data:
    driver: local

networks:
  gupiao_network:
    driver: bridge
